## Main test runner
## Imports all test modules

import unittest2

import ./test_serialize
import ./test_crypto
import ./test_address
import ./test_script
import ./test_witness_cleanstack
import ./test_witness_pubkeytype
import ./test_minimalif
import ./test_tapscript_validation_weight
import ./test_taproot_commitment
import ./test_taproot_p1_gaps
import ./test_taproot_op_success
import ./test_w94_taproot_gates
import ./test_w95_bip340_schnorr
import ./test_mtp_blockheader
import ./test_w85_contextual_block_header
import ./test_consensus
import ./test_consensus_bypass_unification
import ./test_storage
import ./test_messages
import ./test_peer
import ./test_serving
import ./test_mempool
import ./test_chainstate
import ./test_undo
import ./test_fees
import ./test_template
import ./test_sync
import ./test_headerssync
import ./test_wallet
import ./test_bip32_bip86_vectors
import ./test_coinselection
import ./test_maturity
import ./test_encrypt
import ./test_label
import ./test_wallet_persist
import ./test_rpc
import ./test_reject_token_remap
import ./test_getnodeaddresses
import ./test_rpc_thread_lifetime
import ./test_perf
import ./test_sequence_lock
import ./test_bip68
import ./test_isfinaltx
import ./test_cltv
import ./test_sigop
import ./test_difficulty
import ./test_misbehavior
import ./test_banman
import ./test_versionbits
import ./test_handshake
import ./test_pre_handshake
import ./test_relay
import ./test_netgroup
import ./test_eviction
import ./test_anchor
import ./test_eclipse
import ./test_blockstore
import ./test_pruner
import ./test_utxo_cache
import ./test_gcs
import ./test_txindex
import ./test_blockfilter
import ./test_coinstatsindex
import ./test_muhash_vectors
import ./test_compact_blocks
import ./test_psbt
import ./test_bip174
import ./test_descriptor
import ./test_miniscript
import ./test_feefilter
import ./test_cluster
import ./test_p2a
import ./test_rest
import ./test_zmq
import ./test_notification
import ./test_regtest
import ./test_softforks_bridge
import ./test_wallet_dispatch
import ./test_wallet_phase2_segwitv0
import ./test_p2sh_commitment
import ./test_assumevalid
import ./test_checkpoint
import ./test_parallel_verify_ibd
import ./test_bip324
import ./test_rbf
import ./test_standard
import ./test_witness_standard
import ./test_bip331
import ./test_mempool_persist
import ./test_ops
import ./test_snapshot
import ./test_weight_vsize
import ./test_bip141_witness_commitment
import ./test_truc
import ./test_bip30
import ./test_csv_comprehensive
import ./test_bip66
import ./test_mempool_eviction_w86
import ./test_disconnect_block
import ./test_connect_block_w93
import ./test_validateblock_ibd_utxo
import ./test_ibd_durability
import ./test_w117_proxy_wireup
import ./test_w135_standardness
import ./test_w167_getblockstats
import ./test_witness_consensus_fixes
import ./test_w170_tapscript_codesep_sighash
import ./test_wtxid_getdata
import ./test_script_flag_exceptions
import ./test_createrawtx_vout_range

when isMainModule:
  echo "Running all tests..."
