## Main test runner
## Imports all test modules

import unittest2

import ./test_serialize
import ./test_crypto
import ./test_address
import ./test_script
import ./test_sighash
import ./test_witness_cleanstack
import ./test_witness_pubkeytype
import ./test_minimalif
import ./test_consensus
import ./test_storage
import ./test_messages
import ./test_peer
import ./test_mempool
import ./test_chainstate
import ./test_undo
import ./test_fees
import ./test_template
import ./test_sync
import ./test_headerssync
import ./test_wallet
import ./test_coinselection
import ./test_maturity
import ./test_encrypt
import ./test_label
import ./test_rpc
import ./test_rpc_thread_lifetime
import ./test_perf
import ./test_sequence_lock
import ./test_bip68
import ./test_sigop
import ./test_difficulty
import ./test_misbehavior
import ./test_banman
import ./test_versionbits
import ./test_handshake
import ./test_pre_handshake
import ./test_relay
import ./test_netgroup
import ./test_eviction
import ./test_anchor
import ./test_eclipse
import ./test_blockstore
import ./test_utxo_cache
import ./test_gcs
import ./test_txindex
import ./test_blockfilter
import ./test_coinstatsindex
import ./test_compact_blocks
import ./test_psbt
import ./test_bip174
import ./test_descriptor
import ./test_miniscript
import ./test_feefilter
import ./test_cluster
import ./test_p2a
import ./test_rest
import ./test_zmq
import ./test_notification
import ./test_regtest
import ./test_softforks_bridge
import ./test_assumevalid
import ./test_checkpoint
import ./test_parallel_verify_ibd
import ./test_bip324

when isMainModule:
  echo "Running all tests..."
