## Main test runner -- `nimble test` builds and runs THIS file.
##
## It imports every `tests/test_*.nim` except the files named in
## `ExcludedTests` below, and it prints a coverage manifest so that a test file
## which is on disk but not in the run can never again be invisible.
##
## WHY THIS FILE LOOKS LIKE THIS (2026-09-06)
## ------------------------------------------
## It used to be a hand-written list of 112 `import ./test_x` lines, and it
## reported green over a failing run.  Two stacked defects:
##
##   1. 112 of the 224 `tests/test_*.nim` files were imported.  The other 112,
##      holding 2,921 declared tests, were never compiled and never run.  There
##      was nothing to notice: a test file that nobody imports produces no
##      output at all.
##
##   2. The `[Summary]` line is unittest2's own counter.  83 of the 112
##      imported modules used `unittest2`; the other 29 used stdlib
##      `std/unittest`, a separate framework with a separate reporter and a
##      separate counter.  unittest2 counted its 2,177 and was structurally
##      blind to the other 726 -- including all 17 failures that run had.
##      2,177 + 726 = 2,903, and the printed line said
##      `2177 tests run: 2177 OK, 0 FAILED`.
##
## The fixes, in the same order:
##
##   1. The import list is generated by `importTestModules` from the explicit
##      `IncludedTests` array below, and a compile-time guard cross-checks that
##      array plus `ExcludedTests` against what is actually in `tests/`.  Drop a
##      new `test_*.nim` in and forget to list it and the BUILD FAILS naming the
##      file -- it cannot go quiet.
##
##   2. Every test module in `tests/` now uses `unittest2`.  75 files that used
##      stdlib `std/unittest` were converted.  One framework means one reporter
##      and one counter, so `[Summary]` is complete by construction rather than
##      by anyone remembering to keep two numbers in sync.
##
## Anything that genuinely cannot be in the run is named, with its reason, in
## `ExcludedTests`, and `[Coverage]` prints that list after every run.
##
## `nimble test` == `nim c -r tests/test_all.nim`.  Individual files still
## compile and run standalone; `./run-all-tests.sh` does that for all of them
## (slow: one nim compile per file).

import std/[os, strutils]
import ./aggregate_support

const TestsDir = currentSourcePath().parentDir()

## Files that are NOT in this binary.  Each one is printed after every run.
## Adding an entry here is the ONLY sanctioned way to leave a test file out.
const ExcludedTests: seq[ExcludedTest] = @[
  ("test_bench_crypto",
   "does not compile: `Duration.inMicroseconds` (Nim 2.2 std/times) -- tests/test_bench_crypto.nim(62,42)"),
  ("test_ephemeral",
   "does not compile: `contains(string, string)` without std/strutils -- tests/test_ephemeral.nim(164,19)"),
  ("test_erlay",
   "does not compile: undeclared `parseHexInt` (missing std/strutils) -- tests/test_erlay.nim(14,22)"),
  ("test_fix64_tls",
   "binds/connects random TCP ports 20000-60000 on 127.0.0.1 (pickEphemeralPort); collides with reserved ranges on maxbox. Needs a bounded port range before it can join the aggregate."),
  ("test_package",
   "does not compile: undeclared routine `addUtxo` -- tests/test_package.nim(488,7)"),
  ("test_proxy",
   "does not compile: `contains(string, string)` without std/strutils -- tests/test_proxy.nim(25,21)"),
  ("test_script_vectors",
   "declares no unittest cases: `when isMainModule` runner whose main() only prints pass/fail counts, so importing it would add a test that cannot fail. Run it standalone."),
  ("test_sha256_bench",
   "does not compile: `Duration.inMicroseconds` (Nim 2.2 std/times) -- tests/test_sha256_bench.nim(180,44)"),
  ("test_w101_activate_best_chain",
   "does not compile: undeclared `MinBlocksToKeep` -- tests/test_w101_activate_best_chain.nim(748,14)"),
  ("test_w109_block_index",
   "does not compile: undeclared `MinBlocksToKeep` -- tests/test_w109_block_index.nim(815,22)"),
]

## Every other tests/test_*.nim, imported below.  Kept explicit so the set is
## greppable and shows up in review diffs; the compile-time guard keeps it
## honest against the directory.
const IncludedTests = [
  "test_3f_3g_addr_relay_clamp",
  "test_6b_checksigadd_nonminimal_n",
  "test_address",
  "test_addrman_axis2",
  "test_addrv2",
  "test_adopt_applied_block",
  "test_anchor",
  "test_assumeutxo_dual_chainstate",
  "test_assumevalid",
  "test_atmp_w96",
  "test_banman",
  "test_bip141_witness_commitment",
  "test_bip174",
  "test_bip30",
  "test_bip324",
  "test_bip324_w98",
  "test_bip32_bip86_vectors",
  "test_bip331",
  "test_bip66",
  "test_bip68",
  "test_blockfilter",
  "test_blockstore",
  "test_blockwork_exact",
  "test_chain_management",
  "test_chainstate",
  "test_checkpoint",
  "test_cltv",
  "test_cluster",
  "test_coinselection",
  "test_coinstatsindex",
  "test_compact_blocks",
  "test_connect_block_w93",
  "test_consensus",
  "test_consensus_bypass_unification",
  "test_createrawtx_version",
  "test_createrawtx_vout_range",
  "test_crypto",
  "test_csv_comprehensive",
  "test_deep_reorg_archive",
  "test_descriptor",
  "test_difficulty",
  "test_disconnect_block",
  "test_dispatcher_arity",
  "test_eclipse",
  "test_encrypt",
  "test_eviction",
  "test_feefilter",
  "test_fees",
  "test_fix62_bip21",
  "test_fix65_payjoin_receiver",
  "test_fix66_payjoin_sender",
  "test_fix67_payjoin_cleanup",
  "test_fix68_bip125_rpc",
  "test_fix70_wallet_nsequence",
  "test_fix80_getblockheader_ntx",
  "test_fixedseed_fallback",
  "test_fundrawtransaction",
  "test_gcs",
  "test_getblockfrompeer",
  "test_getblockhash_height_range",
  "test_getchainstates",
  "test_getnodeaddresses",
  "test_getorphantxs",
  "test_getpeerinfo_fields",
  "test_handshake",
  "test_headerssync",
  "test_ibd_cache_eviction",
  "test_ibd_durability",
  "test_interpreter_glassbox_fixes",
  "test_isfinaltx",
  "test_label",
  "test_listdescriptors",
  "test_listunspent_regtest_hrp",
  "test_maturity",
  "test_mempool",
  "test_mempool_eviction_w86",
  "test_mempool_persist",
  "test_messages",
  "test_minimalif",
  "test_miniscript",
  "test_minisketch",
  "test_misbehavior",
  "test_mtp_blockheader",
  "test_mtp_sidebranch",
  "test_muhash_vectors",
  "test_netgroup",
  "test_networkdisable",
  "test_nil_db_height_index",
  "test_notification",
  "test_ops",
  "test_orphan_pool",
  "test_p2a",
  "test_p2a_witness",
  "test_p2sh_commitment",
  "test_p2sh_taproot_anyonecspend",
  "test_parallel_verify_ibd",
  "test_peer",
  "test_perf",
  "test_ping_timeout",
  "test_pre_handshake",
  "test_prioritisetransaction",
  "test_pruner",
  "test_psbt",
  "test_psbt_convert_join",
  "test_psbt_emptyvin_gate",
  "test_rbf",
  "test_regtest",
  "test_reject_token_remap",
  "test_relay",
  "test_reorg_coinbase_inflation",
  "test_reorg_p2p",
  "test_rest",
  "test_rpc",
  "test_rpc_conversion_before_lookup",
  "test_rpc_int_arg_bounds",
  "test_rpc_thread_lifetime",
  "test_script",
  "test_script_flag_exceptions",
  "test_sequence_lock",
  "test_serialize",
  "test_serving",
  "test_signrawtransactionwithwallet",
  "test_sigop",
  "test_snapshot",
  "test_softforks_bridge",
  "test_stale_peer",
  "test_standard",
  "test_storage",
  "test_sync",
  "test_taproot_commitment",
  "test_taproot_op_success",
  "test_taproot_p1_gaps",
  "test_tapscript_validation_weight",
  "test_template",
  "test_truc",
  "test_txindex",
  "test_txospenderindex",
  "test_undo",
  "test_utxo_cache",
  "test_validateblock_ibd_utxo",
  "test_versionbits",
  "test_w100_coins_view_cache",
  "test_w103_tx_relay",
  "test_w104_addrman",
  "test_w105_checkqueue",
  "test_w106_mempool",
  "test_w107_compactsize",
  "test_w108_gbt",
  "test_w110_bloom_filter",
  "test_w111_wallet",
  "test_w112_compact_blocks",
  "test_w113_coin_selection",
  "test_w114_fee_estimation",
  "test_w115_asmap",
  "test_w116_package_relay",
  "test_w117_bip155_networks",
  "test_w117_proxy_wireup",
  "test_w118_wallet",
  "test_w119_payjoin",
  "test_w120_mempool_rbf",
  "test_w121_compact_filters",
  "test_w122_codec_stress",
  "test_w123_mining_gbt",
  "test_w124_operator",
  "test_w125_error_parity",
  "test_w125_node_mgmt_error_codes",
  "test_w126_bip152_compact_blocks",
  "test_w127_taproot",
  "test_w128_addrman",
  "test_w129_coin_selection",
  "test_w130_bip125_feebumper_rule3",
  "test_w131_descriptors_miniscript",
  "test_w132_nsequence_csv_mtp",
  "test_w133_index_databases",
  "test_w134_bip37_bloom_filter",
  "test_w135_parsehashv_neg8",
  "test_w135_standardness",
  "test_w136_relay_flags",
  "test_w137_psbt",
  "test_w138_assumeutxo",
  "test_w139_fee_estimation",
  "test_w140_http_rpcauth",
  "test_w141_zmq_rest_notify",
  "test_w160_sig_cache",
  "test_w162_genesis_presync",
  "test_w163_header_chain_reload",
  "test_w164_apply_block_diffbits",
  "test_w165_ibd_tx_inv_suppression",
  "test_w166_apply_block_finality",
  "test_w167_getblockstats",
  "test_w167_verify_pool",
  "test_w168_header_diffbits",
  "test_w168_service_flags",
  "test_w169_feeler_getaddr_antieclipse",
  "test_w170_tapscript_codesep_sighash",
  "test_w171_headertip_livelock",
  "test_w85_contextual_block_header",
  "test_w94_taproot_gates",
  "test_w95_bip340_schnorr",
  "test_w97_accept_block",
  "test_w99_net_processing",
  "test_wallet",
  "test_wallet_dispatch",
  "test_wallet_persist",
  "test_wallet_phase2_segwitv0",
  "test_walletprocesspsbt",
  "test_weight_vsize",
  "test_witness_cleanstack",
  "test_witness_consensus_fixes",
  "test_witness_malleated_p2sh",
  "test_witness_pubkeytype",
  "test_witness_standard",
  "test_wtxid_getdata",
  "test_zmq",
]

## Every tests/test_*.nim actually present, read at COMPILE time.  This is the
## denominator the guard below and the [Coverage] line are measured against.
const OnDiskTests = discoverTestModules(TestsDir)

static:
  ## Completeness guard.  Fails the BUILD -- not a runtime warning -- if a
  ## tests/test_*.nim exists that is neither imported nor explicitly excluded,
  ## or if either list names a file that no longer exists.
  doAssert OnDiskTests.len > 100,
    "test discovery found only " & $OnDiskTests.len & " files in " & TestsDir &
    " -- refusing to build an aggregate that cannot see the test suite"

  var excludedNames: seq[string]
  for e in ExcludedTests: excludedNames.add e.module

  var unaccounted: seq[string]
  for m in OnDiskTests:
    if m notin IncludedTests and m notin excludedNames: unaccounted.add m
  doAssert unaccounted.len == 0,
    "tests/test_all.nim accounts for neither importing nor excluding: " &
    unaccounted.join(", ") &
    " -- add each to IncludedTests, or to ExcludedTests with a reason"

  var ghosts: seq[string]
  for m in IncludedTests:
    if m notin OnDiskTests: ghosts.add m
  for m in excludedNames:
    if m notin OnDiskTests: ghosts.add m
  doAssert ghosts.len == 0,
    "tests/test_all.nim lists files that are not on disk: " & ghosts.join(", ")

importTestModules(TestsDir, IncludedTests)

when isMainModule:
  covOnDisk = OnDiskTests.len
  covIncluded = IncludedTests.len
  covExcluded = ExcludedTests
  echo "Running all tests (", covIncluded, " test modules, ",
       ExcludedTests.len, " excluded -- see [Coverage] below the summary)..."
